watermarking_key_args: # path to the watermarking key (output of keygen.py)
  name: trw
  key_ckpt: pretrained_models/trw-stable-diffusion-2-base.pt # local or remote path

model_args: # arguments to instantiate the model.
  model_name: stable-diffusion-2
  model_ckpt: stabilityai/stable-diffusion-2-1
  scheduler_timesteps: 20

detect_args:
  image_folder: generated_images/trw001     # the folder name where all (potentially) watermarked images are stored

env_args: # Machine specs. If out of memory, reduce batch-size.
  batch_size: 16